---
- name: variables from files
  hosts: web
  tasks:
    - name: print the course information
      ansible.builtin.debug:
        msg: Course is {{ COURSE }}, Duration is {{ DURATION }} ,Tainer is {{ TRAINER }}